server {
    listen 80;
    server_name localhost;

    location / {
        rewrite ^/$ /index.html break;
        proxy_pass http://minio:9000/meu-site/;
        proxy_set_header Host $http_host;
    }

    error_page 404 = /error.html;
}